In [1]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("../dataset/jantung.csv", delimiter=';', decimal=',')
df.head()

BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  MentalHealth     Sex  \
0  16.60     Yes              No     No               1             3  Female   
1  20.34      No              No    Yes               0             0  Female   
2  26.58     Yes              No     No               3             3    Male   
3  24.21      No              No     No               0             0  Female   
4  23.71      No              No     No               3             0  Female   

   AgeCategory Diabetic PhysicalActivity  GenHealth  SleepTime KidneyDisease  \
0        55-59      Yes              Yes  Very good          5            No   
1  80 or older       No              Yes  Very good          7            No   
2        65-69      Yes              Yes       Fair          8            No   
3        75-79       No               No       Good          6            No   
4        40-44       No              Yes  Very good          8            No   

  HeartDisease  
0           No  
1           No  
2           No  
3           No  
4           No

In [3]:
df = df.sample(frac = 1)

In [7]:
df["Diabetic"].unique()

array(['Good', 'Very good', 'Excellent', 'Fair', 'Poor'], dtype=object)

In [164]:
df["Smoking"] = df['Smoking'].replace(['Yes', 'No'], ["1", "0"])
df["AlcoholDrinking"] = df['AlcoholDrinking'].replace(['Yes', 'No'], ["1", "0"])
df["Stroke"] = df['Stroke'].replace(['Yes', 'No'], ["1", "0"])
df["Sex"] = df['Sex'].replace(['Male', 'Female'], ["1", "0"])

arrAgeCategory = list(map(str, [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]))
#df["AgeCategory"] = df['AgeCategory'].replace(['18-24', '25-29', '30-34', '35-39', '40-44', '45-49', '50-54', '55-59', '60-64','65-69','70-74', '75-79', '80 or older'], arrAgeCategory)
#df["Diabetic"] = df['AlcoholDrinking'].replace(['Yes', 'Yes (during pregnancy)', 'No, borderline diabetes', 'No'], ["3", "2", "1", "0"])
#df["GenHealth"] = df['GenHealth'].replace(['Poor', 'Fair', 'Good','Very good', 'Excellent'], list(map(str, [0, 1, 2, 3, 4])))

df["PhysicalActivity"] = df['PhysicalActivity'].replace(['Yes', 'No'], ["1", "0"])
df["KidneyDisease"] = df['KidneyDisease'].replace(['Yes', 'No'], ["1", "0"])
df["HeartDisease"] = df['HeartDisease'].replace(['Yes', 'No'], ["1", "0"])

import category_encoders as ce
# Buat objek ordinal encoder
ordinal_encoder = ce.OrdinalEncoder(cols=['AgeCategory'], mapping=[{'col': 'AgeCategory', 'mapping': {'18-24': 1, '25-29': 2, '30-34': 3, '35-39': 4, '40-44': 5, '45-49': 6, '50-54': 7, '55-59': 8, '60-64': 9, '65-69': 10, '70-74': 11, '75-79': 12, '80 or older': 13}}])
# Lakukan ordinal encoding pada kolom "AgeCategory"
df = ordinal_encoder.fit_transform(df)

ordinal_encoder = ce.OrdinalEncoder(cols=['GenHealth'], mapping=[{'col': 'GenHealth', 'mapping': {'Poor': 1, 'Fair': 2, 'Good': 3, 'Very good': 4, 'Excellent': 5}}])
# Lakukan ordinal encoding pada kolom "GenHealth"
df = ordinal_encoder.fit_transform(df)

ordinal_encoder = ce.OrdinalEncoder(cols=['Diabetic'], mapping=[{'col': 'Diabetic', 'mapping': {'No': 1, 'No, borderline diabetes': 2, 'Yes (during pregnancy)': 3, 'Yes': 4}}])
# Lakukan ordinal encoding pada kolom "Diabetic"
df = ordinal_encoder.fit_transform(df)

df

BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  MentalHealth Sex  \
16628  29.95       0               0      0               0             0   0   
18600  33.91       0               0      0               0             1   1   
17084  24.41       1               0      0               0             0   1   
8020   22.96       1               0      0               0             0   1   
3705   23.44       0               0      0               0             0   0   
...      ...     ...             ...    ...             ...           ...  ..   
10403  36.28       0               0      0               0             0   0   
6069   32.49       1               1      0               0             0   0   
13944  28.27       0               0      0               0             1   1   
6444   31.17       1               0      0               0             0   1   
10668  22.50       0               0      0               0             0   1   

       AgeCategory  Diabetic PhysicalActivity  GenHealth  SleepTime  \
16628            6         1                1          4          7   
18600            3         1                1          4          8   
17084            9         1                1          5          6   
8020            12         1                1          4          6   
3705            12         1                1          4          7   
...            ...       ...              ...        ...        ...   
10403            3         1                1          3          7   
6069             3         1                0          5          5   
13944           11         1                1          3          7   
6444            11         1                1          3          7   
10668           13         1                0          4          7   

      KidneyDisease HeartDisease  
16628             0            0  
18600             0            0  
17084             0            0  
8020              0            0  
3705              0            0  
...             ...          ...  
10403             0            0  
6069              0            0  
13944             1            0  
6444              0            0  
10668             0            1  

[21058 rows x 14 columns]

In [165]:
from sklearn.preprocessing import MinMaxScaler

scaler_bmi = MinMaxScaler()
df[['BMI']] = scaler_bmi.fit_transform(df[['BMI']])

df

BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  MentalHealth  \
16628  0.248584       0               0      0               0             0   
18600  0.304674       0               0      0               0             1   
17084  0.170113       1               0      0               0             0   
8020   0.149575       1               0      0               0             0   
3705   0.156374       0               0      0               0             0   
...         ...     ...             ...    ...             ...           ...   
10403  0.338244       0               0      0               0             0   
6069   0.284561       1               1      0               0             0   
13944  0.224788       0               0      0               0             1   
6444   0.265864       1               0      0               0             0   
10668  0.143059       0               0      0               0             0   

      Sex  AgeCategory  Diabetic PhysicalActivity  GenHealth  SleepTime  \
16628   0            6         1                1          4          7   
18600   1            3         1                1          4          8   
17084   1            9         1                1          5          6   
8020    1           12         1                1          4          6   
3705    0           12         1                1          4          7   
...    ..          ...       ...              ...        ...        ...   
10403   0            3         1                1          3          7   
6069    0            3         1                0          5          5   
13944   1           11         1                1          3          7   
6444    1           11         1                1          3          7   
10668   1           13         1                0          4          7   

      KidneyDisease HeartDisease  
16628             0            0  
18600             0            0  
17084             0            0  
8020              0            0  
3705              0            0  
...             ...          ...  
10403             0            0  
6069              0            0  
13944             1            0  
6444              0            0  
10668             0            1  

[21058 rows x 14 columns]

In [166]:
# Bagi data menjadi training, validation, dan testing sets
train, temp = train_test_split(df, train_size=0.9, random_state=42, shuffle=False)
validation, test = train_test_split(temp, train_size=0.5, random_state=42, shuffle=False)

In [167]:
# Pisahkan fitur dan target untuk masing-masing set
classColumn = "HeartDisease"

train_feature = train.drop(classColumn, axis=1)
train_target = train[classColumn]

validation_feature = validation.drop(classColumn, axis=1)
validation_target = validation[classColumn]

test_feature = test.drop(classColumn, axis=1)
test_target = test[classColumn]

train_target

16628    0
18600    0
17084    0
8020     0
3705     0
        ..
10152    0
7764     0
4497     0
6942     0
3771     1
Name: HeartDisease, Length: 18952, dtype: object

In [168]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature, train_target)

# Evaluasi model pada data validation
y_pred_validation = model.predict(validation_feature)
print("Validation classification_report:\n" + str(classification_report(validation_target, y_pred_validation)))
print("Validation confusion_matrix:\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("Validation accuracy_score:\n" + str(accuracy_score(validation_target, y_pred_validation)))

print("\n\n")
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Validation classification_report:
              precision    recall  f1-score   support

           0       0.92      0.91      0.92       953
           1       0.23      0.25      0.24       100

    accuracy                           0.85      1053
   macro avg       0.57      0.58      0.58      1053
weighted avg       0.85      0.85      0.85      1053

Validation confusion_matrix:
[[868  85]
 [ 75  25]]
Validation accuracy_score:
0.8480531813865148



Test classification_report:
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       952
           1       0.26      0.28      0.27       101

    accuracy                           0.86      1053
   macro avg       0.59      0.60      0.60      1053
weighted avg       0.86      0.86      0.86      1053

Test confusion_matrix:
[[874  78]
 [ 73  28]]
Test accuracy_score:
0.8566001899335233


In [169]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(train_feature, train_target)
y_pred_validation = model.predict(validation_feature)

print("classification_report :\n" + str(classification_report(validation_target, y_pred_validation)))
print("confusion_matrix :\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("accuracy_score :\n" + str(accuracy_score(validation_target, y_pred_validation)))

print("\n\n")

# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

classification_report :
              precision    recall  f1-score   support

           0       0.91      0.98      0.94       953
           1       0.28      0.08      0.12       100

    accuracy                           0.89      1053
   macro avg       0.59      0.53      0.53      1053
weighted avg       0.85      0.89      0.87      1053

confusion_matrix :
[[932  21]
 [ 92   8]]
accuracy_score :
0.8926875593542261



Test classification_report:
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       952
           1       0.50      0.15      0.23       101

    accuracy                           0.90      1053
   macro avg       0.71      0.57      0.59      1053
weighted avg       0.88      0.90      0.88      1053

Test confusion_matrix:
[[937  15]
 [ 86  15]]
Test accuracy_score:
0.9040835707502374


In [171]:
import pickle

pth = ""
# save the model to disk
filename = pth+'jantung.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)

with open('scaler_bmi.pkl', 'wb') as file:
    pickle.dump(scaler_bmi, file)