In [60]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [61]:
df = pd.read_csv("../dataset/hipertensi.csv")
df = df.sample(frac = 1)
df.head()

Age  BMI  Sex  Physical_activity  salt_content_in_the_diet  \
276    65   45    0                  2                         3   
60     71   45    0                  2                         3   
1124   70   23    1                  1                         2   
736    57   17    1                  2                         2   
1014   58   15    1                  2                         2   

      Level_of_Stress  Adrenal_and_thyroid_disorders  \
276                 2                              0   
60                  2                              0   
1124                1                              1   
736                 3                              0   
1014                3                              0   

      Blood_Pressure_Abnormality  
276                            0  
60                             0  
1124                           1  
736                            0  
1014                           1

In [62]:
df["Adrenal_and_thyroid_disorders"].unique()

array([0, 1], dtype=int64)

In [63]:
# MENGUBAH KATEGORIKAL STRING MENJADI NUMERIK YANG DAPAT DIARTIKAN/DILEVELKAN
# CONTOH: low = 0, medium = 1, high = 2

# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# df['Physical_activity'] = le.fit_transform(df['Physical_activity'])
# le = LabelEncoder()
# df['salt_content_in_the_diet'] = le.fit_transform(df['salt_content_in_the_diet'])
# le = LabelEncoder()
# df['Level_of_Stress'] = le.fit_transform(df['Level_of_Stress'])
# df

In [64]:
# NORMALISASI MANUAL

# age_min = df['age'].min()
# age_max = df['age'].max()

# # Lakukan Min-Max Scaling pada fitur "umur"
# df['age'] = (df['age'] - age_min) / (age_max - age_min)
# df

In [65]:
from sklearn.preprocessing import MinMaxScaler

scaler_age = MinMaxScaler()
df[['Age']] = scaler_age.fit_transform(df[['Age']])
scaler_bmi = MinMaxScaler()
df[['BMI']] = scaler_bmi.fit_transform(df[['BMI']])
df

Age    BMI  Sex  Physical_activity  salt_content_in_the_diet  \
276   0.824561  0.875    0                  2                         3   
60    0.929825  0.875    0                  2                         3   
1124  0.912281  0.325    1                  1                         2   
736   0.684211  0.175    1                  2                         2   
1014  0.701754  0.125    1                  2                         2   
...        ...    ...  ...                ...                       ...   
1443  0.614035  0.625    1                  2                         2   
646   0.543860  0.000    0                  1                         2   
420   0.228070  0.100    0                  2                         2   
40    0.052632  0.225    0                  2                         1   
1903  0.245614  0.025    1                  2                         2   

      Level_of_Stress  Adrenal_and_thyroid_disorders  \
276                 2                              0   
60                  2                              0   
1124                1                              1   
736                 3                              0   
1014                3                              0   
...               ...                            ...   
1443                3                              1   
646                 1                              0   
420                 2                              0   
40                  2                              1   
1903                3                              0   

      Blood_Pressure_Abnormality  
276                            0  
60                             0  
1124                           1  
736                            0  
1014                           1  
...                          ...  
1443                           1  
646                            0  
420                            0  
40                             1  
1903                           1  

[2000 rows x 8 columns]

In [66]:
# df = pd.get_dummies(df, columns=['Physical_activity'], prefix='Physical_activity')
# df = pd.get_dummies(df, columns=['salt_content_in_the_diet'], prefix='salt_content_in_the_diet')
# df = pd.get_dummies(df, columns=['Level_of_Stress'], prefix='Level_of_Stress')
# df

In [67]:
# df["Physical_activity"] = pd.Categorical(df["Physical_activity"], categories=[1, 2, 3], ordered=True)
# df["salt_content_in_the_diet"] = pd.Categorical(df["salt_content_in_the_diet"], categories=[1, 2, 3], ordered=True)
# df["Level_of_Stress"] = pd.Categorical(df["Level_of_Stress"], categories=[1, 2, 3], ordered=True)

In [68]:
# Bagi data menjadi training, validation, dan testing sets
train, temp = train_test_split(df, train_size=0.8, random_state=42, shuffle=False)
validation, test = train_test_split(temp, train_size=0.5, random_state=42, shuffle=False)

In [69]:
# Pisahkan fitur dan target untuk masing-masing set
classColumn = "Blood_Pressure_Abnormality"

train_feature = train.drop(classColumn, axis=1)
train_target = train[classColumn]

validation_feature = validation.drop(classColumn, axis=1)
validation_target = validation[classColumn]

test_feature = test.drop(classColumn, axis=1)
test_target = test[classColumn]

train_target

276     0
60      0
1124    1
736     0
1014    1
       ..
1921    0
1618    0
1819    0
921     1
801     0
Name: Blood_Pressure_Abnormality, Length: 1600, dtype: int64

In [70]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature, train_target)

# Evaluasi model pada data validation
y_pred_validation = model.predict(validation_feature)
print("Validation classification_report:\n" + str(classification_report(validation_target, y_pred_validation)))
print("Validation confusion_matrix:\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("Validation accuracy_score:\n" + str(accuracy_score(validation_target, y_pred_validation)))

print()

Validation classification_report:
              precision    recall  f1-score   support

           0       0.54      0.57      0.56        98
           1       0.57      0.54      0.55       102

    accuracy                           0.56       200
   macro avg       0.56      0.56      0.55       200
weighted avg       0.56      0.56      0.55       200

Validation confusion_matrix:
[[56 42]
 [47 55]]
Validation accuracy_score:
0.555



In [71]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

print("\n\n")

# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       0.52      0.54      0.53        99
           1       0.53      0.51      0.52       101

    accuracy                           0.53       200
   macro avg       0.53      0.53      0.52       200
weighted avg       0.53      0.53      0.52       200

Test confusion_matrix:
[[53 46]
 [49 52]]
Test accuracy_score:
0.525



Test classification_report:
              precision    recall  f1-score   support

           0       0.52      0.54      0.53        99
           1       0.53      0.51      0.52       101

    accuracy                           0.53       200
   macro avg       0.53      0.53      0.52       200
weighted avg       0.53      0.53      0.52       200

Test confusion_matrix:
[[53 46]
 [49 52]]
Test accuracy_score:
0.525


In [72]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(train_feature, train_target)
y_pred_validation = model.predict(validation_feature)

print("classification_report :\n" + str(classification_report(validation_target, y_pred_validation)))
print("confusion_matrix :\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("accuracy_score :\n" + str(accuracy_score(validation_target, y_pred_validation)))

print("\n\n")

# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

classification_report :
              precision    recall  f1-score   support

           0       0.55      0.60      0.58        98
           1       0.58      0.53      0.55       102

    accuracy                           0.56       200
   macro avg       0.57      0.57      0.56       200
weighted avg       0.57      0.56      0.56       200

confusion_matrix :
[[59 39]
 [48 54]]
accuracy_score :
0.565



Test classification_report:
              precision    recall  f1-score   support

           0       0.58      0.60      0.59        99
           1       0.59      0.57      0.58       101

    accuracy                           0.58       200
   macro avg       0.59      0.59      0.58       200
weighted avg       0.59      0.58      0.58       200

Test confusion_matrix:
[[59 40]
 [43 58]]
Test accuracy_score:
0.585


In [73]:
import pickle

pth = ""
# save the model to disk
filename = pth+'hipertensi.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)


with open('scaler_age.pkl', 'wb') as file:
    pickle.dump(scaler_age, file)

with open('scaler_bmi.pkl', 'wb') as file:
    pickle.dump(scaler_bmi, file)