In [105]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [106]:
df = pd.read_csv("../dataset/hipertensi.csv")
dfx = df
df = df.sample(frac = 1)
df.head()

Age  BMI  Sex  Physical_activity  salt_content_in_the_diet  \
158    67   46    1                  1                         2   
1495   71   25    0                  2                         3   
1140   52   36    1                  2                         2   
923    75   29    1                  2                         2   
1712   45   15    0                  2                         2   

      Level_of_Stress  Adrenal_and_thyroid_disorders  \
158                 1                              0   
1495                2                              0   
1140                2                              1   
923                 3                              1   
1712                2                              0   

      Blood_Pressure_Abnormality  
158                            1  
1495                           1  
1140                           1  
923                            1  
1712                           0

In [107]:
df["Adrenal_and_thyroid_disorders"].unique()

array([0, 1], dtype=int64)

In [108]:
# MENGUBAH KATEGORIKAL STRING MENJADI NUMERIK YANG DAPAT DIARTIKAN/DILEVELKAN
# CONTOH: low = 0, medium = 1, high = 2

# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# df['Physical_activity'] = le.fit_transform(df['Physical_activity'])
# le = LabelEncoder()
# df['salt_content_in_the_diet'] = le.fit_transform(df['salt_content_in_the_diet'])
# le = LabelEncoder()
# df['Level_of_Stress'] = le.fit_transform(df['Level_of_Stress'])
# df

In [109]:
# NORMALISASI MANUAL

# age_min = df['age'].min()
# age_max = df['age'].max()

# # Lakukan Min-Max Scaling pada fitur "umur"
# df['age'] = (df['age'] - age_min) / (age_max - age_min)
# df

In [110]:
from sklearn.preprocessing import MinMaxScaler

scaler_age = MinMaxScaler()
df[['Age']] = scaler_age.fit_transform(df[['Age']])
scaler_bmi = MinMaxScaler()
df[['BMI']] = scaler_bmi.fit_transform(df[['BMI']])
df

Age    BMI  Sex  Physical_activity  salt_content_in_the_diet  \
158   0.859649  0.900    1                  1                         2   
1495  0.929825  0.375    0                  2                         3   
1140  0.596491  0.650    1                  2                         2   
923   1.000000  0.475    1                  2                         2   
1712  0.473684  0.125    0                  2                         2   
...        ...    ...  ...                ...                       ...   
435   0.333333  0.950    1                  1                         1   
1226  0.298246  0.350    0                  2                         3   
1920  0.964912  0.600    0                  2                         3   
209   0.017544  0.725    0                  2                         2   
831   0.403509  0.025    0                  2                         3   

      Level_of_Stress  Adrenal_and_thyroid_disorders  \
158                 1                              0   
1495                2                              0   
1140                2                              1   
923                 3                              1   
1712                2                              0   
...               ...                            ...   
435                 1                              1   
1226                3                              0   
1920                2                              0   
209                 2                              1   
831                 3                              1   

      Blood_Pressure_Abnormality  
158                            1  
1495                           1  
1140                           1  
923                            1  
1712                           0  
...                          ...  
435                            0  
1226                           0  
1920                           0  
209                            1  
831                            0  

[2000 rows x 8 columns]

In [111]:
# df = pd.get_dummies(df, columns=['Physical_activity'], prefix='Physical_activity')
# df = pd.get_dummies(df, columns=['salt_content_in_the_diet'], prefix='salt_content_in_the_diet')
# df = pd.get_dummies(df, columns=['Level_of_Stress'], prefix='Level_of_Stress')
# df

In [112]:
df["Physical_activity"] = pd.Categorical(df["Physical_activity"], categories=[1, 2, 3], ordered=True)
df["salt_content_in_the_diet"] = pd.Categorical(df["salt_content_in_the_diet"], categories=[1, 2, 3], ordered=True)
df["Level_of_Stress"] = pd.Categorical(df["Level_of_Stress"], categories=[1, 2, 3], ordered=True)

In [113]:
# Bagi data menjadi training, validation, dan testing sets
train, temp = train_test_split(df, train_size=0.8, random_state=42, shuffle=False)
validation, test = train_test_split(temp, train_size=0.5, random_state=42, shuffle=False)

In [114]:
# Pisahkan fitur dan target untuk masing-masing set
classColumn = "Blood_Pressure_Abnormality"

train_feature = train.drop(classColumn, axis=1)
train_target = train[classColumn]

validation_feature = validation.drop(classColumn, axis=1)
validation_target = validation[classColumn]

test_feature = test.drop(classColumn, axis=1)
test_target = test[classColumn]

train_target

158     1
1495    1
1140    1
923     1
1712    0
       ..
882     0
1964    0
424     1
1061    1
1001    1
Name: Blood_Pressure_Abnormality, Length: 1600, dtype: int64

In [115]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature, train_target)

# Evaluasi model pada data validation
y_pred_validation = model.predict(validation_feature)
print("Validation classification_report:\n" + str(classification_report(validation_target, y_pred_validation)))
print("Validation confusion_matrix:\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("Validation accuracy_score:\n" + str(accuracy_score(validation_target, y_pred_validation)))

Validation classification_report:
              precision    recall  f1-score   support

           0       0.49      0.59      0.54        95
           1       0.55      0.45      0.49       105

    accuracy                           0.52       200
   macro avg       0.52      0.52      0.51       200
weighted avg       0.52      0.52      0.51       200

Validation confusion_matrix:
[[56 39]
 [58 47]]
Validation accuracy_score:
0.515


In [116]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       0.58      0.57      0.58       104
           1       0.55      0.56      0.55        96

    accuracy                           0.56       200
   macro avg       0.56      0.56      0.56       200
weighted avg       0.57      0.56      0.57       200

Test confusion_matrix:
[[59 45]
 [42 54]]
Test accuracy_score:
0.565


In [117]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(train_feature, train_target)
y_pred_validation = model.predict(validation_feature)

print("classification_report :\n" + str(classification_report(validation_target, y_pred_validation)))
print("confusion_matrix :\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("accuracy_score :\n" + str(accuracy_score(validation_target, y_pred_validation)))

classification_report :
              precision    recall  f1-score   support

           0       0.53      0.69      0.60        95
           1       0.62      0.45      0.52       105

    accuracy                           0.56       200
   macro avg       0.58      0.57      0.56       200
weighted avg       0.58      0.56      0.56       200

confusion_matrix :
[[66 29]
 [58 47]]
accuracy_score :
0.565


In [118]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       0.62      0.62      0.62       104
           1       0.59      0.59      0.59        96

    accuracy                           0.61       200
   macro avg       0.61      0.61      0.61       200
weighted avg       0.61      0.61      0.61       200

Test confusion_matrix:
[[65 39]
 [39 57]]
Test accuracy_score:
0.61


In [119]:
import pickle

pth = ""
# save the model to disk
filename = pth+'hipertensi.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)


with open('scaler_age.pkl', 'wb') as file:
    pickle.dump(scaler_age, file)

with open('scaler_bmi.pkl', 'wb') as file:
    pickle.dump(scaler_bmi, file)