In [12]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [18]:
df = pd.read_csv("../dataset/diabetes.csv")
df = df.sample(frac = 1)
df.head()

age  gender  polyuria  polydipsia  sudden_weight_loss  polyphagia  \
158   56    Male         1           0                   1           0   
364   35  Female         0           0                   0           0   
440   48    Male         1           1                   0           0   
177   50  Female         1           1                   1           1   
360   56    Male         1           0                   1           0   

     delayed_healing  obesity  class  
158                0        0      1  
364                0        0      1  
440                0        0      1  
177                1        0      1  
360                0        0      1

In [19]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [20]:
df["gender"] = df['gender'].replace(['Male', 'Female'], ["1", "0"])
df

age gender  polyuria  polydipsia  sudden_weight_loss  polyphagia  \
158   56      1         1           0                   1           0   
364   35      0         0           0                   0           0   
440   48      1         1           1                   0           0   
177   50      0         1           1                   1           1   
360   56      1         1           0                   1           0   
..   ...    ...       ...         ...                 ...         ...   
75    55      0         1           1                   1           0   
295   55      0         1           1                   1           0   
510   67      1         0           0                   0           0   
159   38      0         1           1                   1           1   
363   68      0         1           1                   0           1   

     delayed_healing  obesity  class  
158                0        0      1  
364                0        0      1  
440                0        0      1  
177                1        0      1  
360                0        0      1  
..               ...      ...    ...  
75                 0        1      1  
295                0        1      1  
510                1        0      0  
159                1        0      1  
363                1        0      1  

[520 rows x 9 columns]

In [21]:
train, test = train_test_split(df, train_size=0.8, random_state=42, shuffle=False)
train

age gender  polyuria  polydipsia  sudden_weight_loss  polyphagia  \
158   56      1         1           0                   1           0   
364   35      0         0           0                   0           0   
440   48      1         1           1                   0           0   
177   50      0         1           1                   1           1   
360   56      1         1           0                   1           0   
..   ...    ...       ...         ...                 ...         ...   
396   30      1         0           0                   0           0   
387   36      1         0           0                   0           0   
401   36      1         0           0                   0           0   
351   30      1         0           0                   0           0   
100   48      0         1           1                   1           1   

     delayed_healing  obesity  class  
158                0        0      1  
364                0        0      1  
440                0        0      1  
177                1        0      1  
360                0        0      1  
..               ...      ...    ...  
396                0        0      0  
387                0        0      0  
401                0        0      0  
351                0        0      0  
100                1        1      1  

[416 rows x 9 columns]

In [22]:
train_feature = train.loc[:, train.columns != "class"]
train_target = train["class"]

test_feature = test.loc[:, test.columns != "class"]
test_target = test["class"]

In [23]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature,train_target)
y_pred = model.predict(test_feature)

print("classification_report :\n" + str(classification_report(test_target,y_pred)))
print("confusion_matrix :\n" + str(confusion_matrix(test_target,y_pred)))
print("accuracy_score :\n" + str(accuracy_score(test_target,y_pred)))

classification_report :
              precision    recall  f1-score   support

           0       0.96      0.94      0.95        47
           1       0.95      0.96      0.96        57

    accuracy                           0.95       104
   macro avg       0.95      0.95      0.95       104
weighted avg       0.95      0.95      0.95       104

confusion_matrix :
[[44  3]
 [ 2 55]]
accuracy_score :
0.9519230769230769


In [24]:
test_target

485    1
195    1
289    0
146    1
81     1
      ..
75     1
295    1
510    0
159    1
363    1
Name: class, Length: 104, dtype: int64

In [27]:
import pickle

pth = ""
# save the model to disk
filename = pth+'DT.sav'
#pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)

#print("accuracy_score :\n" + str(accuracy_score(test_target, y_pred2)))

0.9807692307692307

In [9]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
model.fit(train_feature,train_target)
y_pred = model.predict(test_feature)

print("classification_report :\n" + str(classification_report(test_target,y_pred)))
print("confusion_matrix :\n" + str(confusion_matrix(test_target,y_pred)))
print("accuracy_score :\n" + str(accuracy_score(test_target,y_pred)))

classification_report :
              precision    recall  f1-score   support

           0       0.90      0.92      0.91        48
           1       0.93      0.91      0.92        56

    accuracy                           0.91       104
   macro avg       0.91      0.91      0.91       104
weighted avg       0.91      0.91      0.91       104

confusion_matrix :
[[44  4]
 [ 5 51]]
accuracy_score :
0.9134615384615384


In [10]:
from sklearn.svm import SVC

model = SVC()
model.fit(train_feature,train_target)
y_pred = model.predict(test_feature)

print("classification_report :\n" + str(classification_report(test_target,y_pred)))
print("confusion_matrix :\n" + str(confusion_matrix(test_target,y_pred)))
print("accuracy_score :\n" + str(accuracy_score(test_target,y_pred)))

classification_report :
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        48
           1       0.54      1.00      0.70        56

    accuracy                           0.54       104
   macro avg       0.27      0.50      0.35       104
weighted avg       0.29      0.54      0.38       104

confusion_matrix :
[[ 0 48]
 [ 0 56]]
accuracy_score :
0.5384615384615384


c:\BANGKIT\TFDS\venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\BANGKIT\TFDS\venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\BANGKIT\TFDS\venv\lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
