In [2973]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [2974]:
df = pd.read_csv("../dataset/diabetes.csv")
df = df.sample(frac = 1)
df.head()

age  gender  polyuria  polydipsia  sudden_weight_loss  polyphagia  \
203   34    Male         0           0                   0           0   
417   39  Female         1           1                   1           1   
295   55  Female         1           1                   1           0   
292   46    Male         0           0                   0           0   
490   46    Male         0           0                   0           0   

     delayed_healing  obesity  class  
203                0        0      0  
417                1        0      1  
295                0        1      1  
292                1        0      0  
490                1        0      0

In [2975]:
df["gender"].unique()

array(['Male', 'Female'], dtype=object)

In [2976]:
# MANUAL
df["gender"] = df['gender'].replace(['Male', 'Female'], ["1", "0"])

#df = pd.get_dummies(df, columns=['gender'])
df

age gender  polyuria  polydipsia  sudden_weight_loss  polyphagia  \
203   34      1         0           0                   0           0   
417   39      0         1           1                   1           1   
295   55      0         1           1                   1           0   
292   46      1         0           0                   0           0   
490   46      1         0           0                   0           0   
..   ...    ...       ...         ...                 ...         ...   
58    59      0         0           0                   0           0   
19    43      1         1           1                   1           0   
25    32      1         0           0                   0           0   
323   44      1         1           0                   1           0   
436   41      1         1           1                   1           1   

     delayed_healing  obesity  class  
203                0        0      0  
417                1        0      1  
295                0        1      1  
292                1        0      0  
490                1        0      0  
..               ...      ...    ...  
58                 0        0      1  
19                 0        0      1  
25                 1        1      1  
323                1        1      0  
436                0        1      1  

[520 rows x 9 columns]

In [2977]:
# MENGUBAH KATEGORIKAL STRING MENJADI NUMERIK YANG DAPAT DIARTIKAN/DILEVELKAN
# CONTOH: low = 0, medium = 1, high = 2

# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# df['level'] = le.fit_transform(df['level'])

In [2978]:
# NORMALISASI MANUAL

# age_min = df['age'].min()
# age_max = df['age'].max()

# # Lakukan Min-Max Scaling pada fitur "umur"
# df['age'] = (df['age'] - age_min) / (age_max - age_min)
# df

In [2979]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df[['age']] = scaler.fit_transform(df[['age']])
df

age gender  polyuria  polydipsia  sudden_weight_loss  polyphagia  \
203  0.243243      1         0           0                   0           0   
417  0.310811      0         1           1                   1           1   
295  0.527027      0         1           1                   1           0   
292  0.405405      1         0           0                   0           0   
490  0.405405      1         0           0                   0           0   
..        ...    ...       ...         ...                 ...         ...   
58   0.581081      0         0           0                   0           0   
19   0.364865      1         1           1                   1           0   
25   0.216216      1         0           0                   0           0   
323  0.378378      1         1           0                   1           0   
436  0.337838      1         1           1                   1           1   

     delayed_healing  obesity  class  
203                0        0      0  
417                1        0      1  
295                0        1      1  
292                1        0      0  
490                1        0      0  
..               ...      ...    ...  
58                 0        0      1  
19                 0        0      1  
25                 1        1      1  
323                1        1      0  
436                0        1      1  

[520 rows x 9 columns]

In [2980]:
# Bagi data menjadi training, validation, dan testing sets
train, temp = train_test_split(df, train_size=0.8, random_state=42, shuffle=False)
validation, test = train_test_split(temp, train_size=0.5, random_state=42, shuffle=False)

In [2981]:
# Pisahkan fitur dan target untuk masing-masing set
train_feature = train.drop("class", axis=1)
train_target = train["class"]

validation_feature = validation.drop("class", axis=1)
validation_target = validation["class"]

test_feature = test.drop("class", axis=1)
test_target = test["class"]

In [2982]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature, train_target)

# Evaluasi model pada data validation
y_pred_validation = model.predict(validation_feature)
print("Validation classification_report:\n" + str(classification_report(validation_target, y_pred_validation)))
print("Validation confusion_matrix:\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("Validation accuracy_score:\n" + str(accuracy_score(validation_target, y_pred_validation)))

Validation classification_report:
              precision    recall  f1-score   support

           0       0.95      0.95      0.95        21
           1       0.97      0.97      0.97        31

    accuracy                           0.96        52
   macro avg       0.96      0.96      0.96        52
weighted avg       0.96      0.96      0.96        52

Validation confusion_matrix:
[[20  1]
 [ 1 30]]
Validation accuracy_score:
0.9615384615384616


In [2983]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       1.00      0.91      0.95        22
           1       0.94      1.00      0.97        30

    accuracy                           0.96        52
   macro avg       0.97      0.95      0.96        52
weighted avg       0.96      0.96      0.96        52

Test confusion_matrix:
[[20  2]
 [ 0 30]]
Test accuracy_score:
0.9615384615384616


In [2984]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(train_feature, train_target)
y_pred_validation = model.predict(validation_feature)

print("classification_report :\n" + str(classification_report(validation_target, y_pred_validation)))
print("confusion_matrix :\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("accuracy_score :\n" + str(accuracy_score(validation_target, y_pred_validation)))

classification_report :
              precision    recall  f1-score   support

           0       1.00      0.90      0.95        21
           1       0.94      1.00      0.97        31

    accuracy                           0.96        52
   macro avg       0.97      0.95      0.96        52
weighted avg       0.96      0.96      0.96        52

confusion_matrix :
[[19  2]
 [ 0 31]]
accuracy_score :
0.9615384615384616


In [2985]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       1.00      0.95      0.98        22
           1       0.97      1.00      0.98        30

    accuracy                           0.98        52
   macro avg       0.98      0.98      0.98        52
weighted avg       0.98      0.98      0.98        52

Test confusion_matrix:
[[21  1]
 [ 0 30]]
Test accuracy_score:
0.9807692307692307


In [2986]:
import pickle

pth = ""
# save the model to disk
filename = pth+'diabetes.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)


with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)