In [154]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

In [155]:
df = pd.read_csv("../dataset/kanker.csv")
df["Level"] = df['Level'].replace(['Low', 'Medium', 'High'], ["0", "1", "2"])
df.head()

df = df.sample(frac = 1)

df

Age  Gender  Air Pollution  OccuPational Hazards  Genetic Risk  Smoking  \
108   37       2              6                     7             7        7   
57    53       2              4                     5             5        2   
61    61       2              2                     2             1        3   
200   45       1              6                     7             7        4   
236   27       2              3                     2             3        2   
..   ...     ...            ...                   ...           ...      ...   
610   47       2              2                     3             2        2   
158   35       1              1                     4             2        2   
457   61       1              2                     2             1        3   
666   47       1              6                     5             5        2   
946   44       1              2                     1             3        7   

     Passive Smoker  Chest Pain  Coughing of Blood  Weight Loss  \
108               8           7                  7            6   
57                3           4                  8            7   
61                2           1                  5            1   
200               8           7                  7            4   
236               2           4                  2            2   
..              ...         ...                ...          ...   
610               1           2                  5            2   
158               1           3                  4            2   
457               2           1                  5            1   
666               3           4                  8            7   
946               6           2                  2            2   

     Shortness of Breath  Wheezing  Dry Cough Level  
108                    5         7          1     2  
57                     9         2          7     2  
61                     3         2          1     0  
200                    5         6          6     2  
236                    3         4          6     0  
..                   ...       ...        ...   ...  
610                    1         2          4     0  
158                    2         2          2     0  
457                    3         2          1     0  
666                    9         2          7     2  
946                    3         2          2     0  

[1000 rows x 14 columns]

In [156]:
df["Level"].unique()

array(['2', '0', '1'], dtype=object)

In [157]:
# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# df['Level'] = le.fit_transform(df['Level'])
# df

In [158]:
# MENGUBAH KATEGORIKAL STRING MENJADI NUMERIK YANG DAPAT DIARTIKAN/DILEVELKAN
# CONTOH: low = 0, medium = 1, high = 2

# from sklearn.preprocessing import LabelEncoder

# le = LabelEncoder()
# df['Physical_activity'] = le.fit_transform(df['Physical_activity'])
# le = LabelEncoder()
# df['salt_content_in_the_diet'] = le.fit_transform(df['salt_content_in_the_diet'])
# le = LabelEncoder()
# df['Level_of_Stress'] = le.fit_transform(df['Level_of_Stress'])
# df

In [159]:
from sklearn.preprocessing import MinMaxScaler

scaler_age = MinMaxScaler()
df[['Age']] = scaler_age.fit_transform(df[['Age']])

In [160]:
# df = pd.get_dummies(df, columns=['Air Pollution'])
# df = pd.get_dummies(df, columns=['OccuPational Hazards'])
# df = pd.get_dummies(df, columns=['Genetic Risk'])
# df = pd.get_dummies(df, columns=['Smoking'])
# df = pd.get_dummies(df, columns=['Passive Smoker'])
# df = pd.get_dummies(df, columns=['Chest Pain'])
# df = pd.get_dummies(df, columns=['Coughing of Blood'])
# df = pd.get_dummies(df, columns=['Weight Loss'])
# df = pd.get_dummies(df, columns=['Shortness of Breath'])
# df = pd.get_dummies(df, columns=['Wheezing'])
# df = pd.get_dummies(df, columns=['Dry Cough'])
# df

In [161]:
# Bagi data menjadi training, validation, dan testing sets
train, temp = train_test_split(df, train_size=0.8, random_state=42, shuffle=False)
validation, test = train_test_split(temp, train_size=0.5, random_state=42, shuffle=False)

In [162]:
# Pisahkan fitur dan target untuk masing-masing set
classColumn = "Level"

train_feature = train.drop(classColumn, axis=1)
train_target = train[classColumn]

validation_feature = validation.drop(classColumn, axis=1)
validation_target = validation[classColumn]

test_feature = test.drop(classColumn, axis=1)
test_target = test[classColumn]

train_target

108    2
57     2
61     0
200    2
236    0
      ..
490    1
845    2
192    1
672    0
406    1
Name: Level, Length: 800, dtype: object

In [163]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = DecisionTreeClassifier()
history = model.fit(train_feature, train_target)

# Evaluasi model pada data validation
y_pred_validation = model.predict(validation_feature)
print("Validation classification_report:\n" + str(classification_report(validation_target, y_pred_validation)))
print("Validation confusion_matrix:\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("Validation accuracy_score:\n" + str(accuracy_score(validation_target, y_pred_validation)))

Validation classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        36
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Validation confusion_matrix:
[[30  0  0]
 [ 0 36  0]
 [ 0  0 34]]
Validation accuracy_score:
1.0


In [164]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        41
           2       1.00      1.00      1.00        30

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Test confusion_matrix:
[[29  0  0]
 [ 0 41  0]
 [ 0  0 30]]
Test accuracy_score:
1.0


In [165]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(train_feature, train_target)
y_pred_validation = model.predict(validation_feature)

print("classification_report :\n" + str(classification_report(validation_target, y_pred_validation)))
print("confusion_matrix :\n" + str(confusion_matrix(validation_target, y_pred_validation)))
print("accuracy_score :\n" + str(accuracy_score(validation_target, y_pred_validation)))

classification_report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        30
           1       1.00      1.00      1.00        36
           2       1.00      1.00      1.00        34

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

confusion_matrix :
[[30  0  0]
 [ 0 36  0]
 [ 0  0 34]]
accuracy_score :
1.0


In [166]:
# Evaluasi model pada data testing
y_pred_test = model.predict(test_feature)
print("Test classification_report:\n" + str(classification_report(test_target, y_pred_test)))
print("Test confusion_matrix:\n" + str(confusion_matrix(test_target, y_pred_test)))
print("Test accuracy_score:\n" + str(accuracy_score(test_target, y_pred_test)))

Test classification_report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        29
           1       1.00      1.00      1.00        41
           2       1.00      1.00      1.00        30

    accuracy                           1.00       100
   macro avg       1.00      1.00      1.00       100
weighted avg       1.00      1.00      1.00       100

Test confusion_matrix:
[[29  0  0]
 [ 0 41  0]
 [ 0  0 30]]
Test accuracy_score:
1.0


In [167]:
import pickle

pth = ""
# save the model to disk
filename = pth+'kanker.sav'
pickle.dump(model, open(filename, 'wb'))
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
loaded_model.score(test_feature, test_target)
#y_pred2 = loaded_model.predict(test_feature)


with open('scaler_age.pkl', 'wb') as file:
    pickle.dump(scaler_age, file)